### ISSUE TITLE
Mod makes mithrix pizza stop your character from sprinting

### ISSUE THREAD

**Issue by Lienep0** [Goorakh/AttackDirectionFix#1]
As the title says. When running around mithrix while he's performing his "pizza" attack in phase 3, character just decides to stop sprinting sometimes when the attack activates (not when it hits, just when the hiboxes appear). Maybe related to the screenshake effect the attack enduces ?

Tested on a fresh profile in r2modman with only DebugToolkit and AttackDirectionFix installed. 
To reproduce the bug :

- Pick e8, commando, default loadout
- Run this command in the console : 
          give_item feather 20
          give_item hoof 20
          give_item dio 100
          give_item fuel 20
          give_equip vase
          give_item boss 500
          no_enemies
          next_stage moon2
- Go to mithrix and kill phase 1 and 2, then fire a single round of your m1 on phase 3 to pass the pizza health threshold
- While he's performing pizza, run around him while sprinting and while not getting hit. Maybe also works if you activate godmode ?

I really hope this gets fixed eventually because I really like this mod but I definitely won't use it anymore since it makes mithrix so much harder. This happens with umbral mithrix too !

Here's a video of the bug happening : 
https://github.com/Goorakh/AttackDirectionFix/assets/119780411/219d2792-1ac8-46f0-94e6-58f3e70df412
(I did not stop sprinting a single time here, this is purely becuase of the attack)

**Comment by Goorakh** [comment]
This is a known issue that I am looking into, I've not tested extensively but screenshake is the main suspect as of now, you could try turning screenshake off and see if that helps?

There's no ETA but I'll push an update as soon as I've got it figured out. Thank you for the detailed report! :)

**Comment by Lienep0** [comment]
Indeed, the mithrix pizza doesn't stop you from sprinting if you have screenshake turned all the way down. 

With more testing, it seems entirely dependant on how much the camera shakes. The bug only happens when close enough to mithrix with 100% screenshake, and that range seems to get smaller and smaller when you reduce the screen shake scale.

**Comment by Goorakh** [comment]
This is now fixed. New version was just uploaded :)
